# Datetime,Time delta,Str_ftime(For different formats of date and time):

import datetime as dt

current_date = dt.date.today()
print("Current Date:", current_date)
new = dt.date(2021, 12, 20)
print(new)
print(new.year)
print(new.month)
print(new.day)
print("-------------------")
a = dt.time(10, 45, 3, 5)
print(a)
print(a.hour)
print(a.minute)
print(a.second)
print(a.microsecond)
print("-------------------------")
current_time = dt.datetime.now()
print("current time :", current_time)
print("-------------------")
new = dt.datetime(2023, 4, 12, 11, 12, 3, 3)
print(new)
print(new.date())
print(new.time())
current_date = dt.datetime.now()
new_year = dt.datetime(2024, 1, 1)
difference = new_year - current_date
print(difference)
print("-------------------------")
current = dt.datetime.now()
print("current time :", current)
s = current.strftime("%A %B %D %Y")
print(s)
print("----------------weekday(Starts with 0 for monday)----------------------")
t_date = dt.date(2023, 5, 16)
print(t_date)
wday = t_date.weekday()
print("weekday:", wday)
print("------------------------iso weekday(Starts with 1 for monday)------------")
iso_day = t_date.isoweekday()
print("weekday:", iso_day)
print("-----------------Time Delta---------------------------")
t_delta = dt.timedelta(days=5)
print("Time delta:", t_date - t_delta)
